default_language_version:
  python: python3
exclude: >
  (?x)^(
      deluge/ui/web/docs/template/.*|
  )$
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Fmt Black
        language_version: python3.6
  - repo: https://github.com/prettier/prettier
    rev: 1.17.0
    hooks:
      - id: prettier
        name: Fmt Prettier
        # Workaround to list modified files only.
        args: [--list-different]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        name: Chk Flake8
        additional_dependencies:
          - flake8-isort==2.7
          - pep8-naming==0.8.2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: double-quote-string-fixer
        name: Fix Double-quotes
      - id: end-of-file-fixer
        name: Fix End-of-files
        exclude_types: [javascript, css]
      - id: mixed-line-ending
        name: Fix Line endings
        args: [--fix=auto]
      - id: trailing-whitespace
        name: Fix Trailing whitespace
