language: python

python:
#    - "2.6"
    - "2.7"

# command to install dependencies
install:
  - pip install tox
  - lsb_release -a
  - sudo add-apt-repository ppa:deluge-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install python-libtorrent

script:
  - tox

env:
  - TOX_ENV=pydef
  - TOX_ENV=plugins
  - TOX_ENV=pep8
  - TOX_ENV=flakes
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=testcoverage

virtualenv:
  system_site_packages: true

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - python -c "import libtorrent as lt; print lt.version"

script:
  - tox -e $TOX_ENV
